# Generated by Django 2.2.6 on 2019-11-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example2Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=2048)),
                ('phone_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Example Two Form',
                'verbose_name_plural': 'Example Two Form',
            },
        ),
    ]
